name: tiny_react
description: Syntax sugar for `ValueNotifier` and `ValueListenableBuilder`. Reactive programming with less boilerplate.
version: 1.1.0
homepage: https://github.com/zuvola/tiny_react

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
